# .github/workflows/parse-build-deploy-pages.yml
name: Parse → Build → Deploy (GitHub Pages)

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write   # коммитить data
  pages: write      # деплоить на Pages
  id-token: write   # OIDC для Pages

jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install parser deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run parser (schedule by default)
        env:
          URL_PROGRAM: "https://project13487951.tilda.ws/page74408851.html"
          PROGRAM_DATE: "2025-09-24"
        run: |
          python tools/tilda_unified_parser.py --update schedule --data-dir public/data

      - id: diff
        name: Detect data changes
        run: |
          if [[ -n "$(git status --porcelain public/data)" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push data
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data
          git commit -m "data: auto-update $(date -u +'%F %T')"
          git push

  build:
    needs: parse
    if: needs.parse.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
